### ISSUE TITLE
HomeKit device not showing up.

### ISSUE THREAD

**Issue by Roelof626** [Kienz/homebridge-unifi-poe-control#1]
I installed the plugin and configured it correct following the description. But in my Home app it won't show a new device to control the PoE Port with. Am I doing something wrong?

I'm using an USW Lite 8 PoE & a UDM Pro as controller.
This is my Config:

` "platforms": [ `
`      { `
`            "platform": "UniFiPoeControl",`
`            "name": "UniFi POE",`
`            "url": "https://192.168.3.1:443",`
`            "username": "xxxxx",`
`            "password": "xxxxx",`
`            "refreshInterval": 60000,`
`            "ports": [`
`                [`
`                    {`
`                        "mac": "xx:xx:xx:xx:xx:xx",`
`                        "idx": 3,`
`                        "name": "CCTV Switch",`
`                        "onMode": "auto"`
`                    }`
`                ]`
`            ]`
`        }`
`    ]`
Of course I blurred out the sensitive information.
Can someone help me please?

P.S. I'm sorry for the code markup

**Comment by Kienz** [comment]
It seems that your JSON is wrong: You declared an array within another array for the ports property:

```json
"ports": [
{
"mac": "xx:xx:xx:xx:xx:xx",
"idx": 3,
"name": "CCTV Switch",
"onMode": "auto"
}
] 
```

**Comment by Roelof626** [comment]
I replaced the "ports" section and now the switch showed up in the accessory tab in the Homebridge UI but not in the home app, It's also not showing up when I try to add a new accessory. I rebooted my iPhone and the complete Homebridge OS multiple times but it didn't worked at all. any ideas on that?

**Comment by Kienz** [comment]
Your Homebridge is added to HomeKit? That’s strange. Did it appear in the Default Room?
Logs?

**Comment by Roelof626** [comment]
My Homebridge controller is added to HomeKit.
My bedroom is the default room, I changed the name of it. it doesn't appear there neither the complete home or bridged accessory's.
I added my log files:
[homebridge.log.txt](https://github.com/Kienz/homebridge-unifi-poe-control/files/7666917/homebridge.log.txt)

**Comment by Kienz** [comment]
Is your mac address lowercase and is it correct?

Please enable debug logging for the homebridge and open after some time the /var/lib/homebridge/homebridge.log file.
Search for `config: {"method":"GET","url":"proxy/network/api/s/default/stat/device"` - the next log output should be the response with a very large JSON object. Copy it and search for your mac address.

**Comment by Roelof626** [comment]
I enabled Debug mode and copied the output log from the 
`config: {"method":"GET","url":"proxy/network/api/s/default/stat/device"` line to the end and searched for my MAC-Address from the switch as you said. I found my MAC-Address 15 times so I don't think that's the problem. The switch in the Homebridge UI is visible and is even working. but it isn't showing up in the Home App as I said earlier.

**Comment by Roelof626** [comment]
Well Ok, I don't know how but it just appeared randomly. The only think I changed is turning on and off the debug mode. I'm sorry for the problem. Thanks anyway for the help!
