### ISSUE TITLE
No Update on Connection

### ISSUE THREAD

**Issue by SaavageBueno** [Kienz/homebridge-unifi-poe-control#11]
After Install, No Log Update containing PoE control, as well as no buttons added for remote control. Unable to see any errors or why the plugin is failing.

**Comment by Kienz** [comment]
Can you give me more infos?

- Logs
- UniFiOS Version
- UniFiOS Console (UDMSE, UDMPRO etc.)
- What do you want to control? Which switch?

**Comment by Kienz** [comment]
@SaavageBueno Did you restart homebridge?
