### ISSUE TITLE
Not possible to switch on passthrough-port on Switchmodel US-8

### ISSUE THREAD

**Issue by ar1970** [Kienz/homebridge-unifi-poe-control#15]
On Unifi switch model us-8 it is possible to configure one port with poe. This port has to be configured with poe 'passtrough' or 'poe off'. It is possible to switch off the port but it is not possible to switch it on via home app (homebridge plugin)! Is it possible to add the value 'Passthrough' to the configuration of the POE ON function? Currently only the settings 'auto', '24V Passive' and 'Power Cycle' are possible.

**Comment by smonsi** [comment]
Hello everyone,
I would also be interested in this feature
