### ISSUE TITLE
Homebridge unable to access poe ports. Code 400

### ISSUE THREAD

**Issue by Daveblanche** [Kienz/homebridge-unifi-poe-control#17]
Hi there
Since the last few updates on unifi, including the addition of Ethernet port profiles, it is increasingly difficult to control or gain access to control the poe ports in this (brilliant) plug in. I do not think it’s an issue with the plug in but with unifi os. Can you help with a workaround, in unifi os, to getting the communication working?

**Comment by Kienz** [comment]
Can you give me more infos?
- Logs
- UniFiOS Version
- UniFiOS Console (UDMSE, UDMPRO etc.)
- What do you want to control? Which switch?

**Comment by Daveblanche** [comment]
Hi there
It was on 3.15 unifi OS, but seems to have settled on 3.16. UDMPro.
Also the present version on Unifi Network (I’m travelling abroad on business so cant get to my network controller at the moment)
The Switch is a USW 48 Port POE, running the up to date firmware. Nothing is beta or early release.
It’s working again since I updated again. Damned Unifi updates. If it happens again, do you mind if I get the logs etc to you.
I’ve also update to 1.3.0 and all seems fine. I am trying to control 3 ports at similar times of day, and have a shortcut to provide 20 second delays. But it all works without the shortcut now, too.
Englisch oder Deutsch.
Ich bedanke mich.
