### ISSUE TITLE
time schedule

### ISSUE THREAD

**Issue by BeckeBauer** [Kienz/homebridge-unifi-poe-control#19]
Is it possible to set a time schedule for ports to be deactivated and activated so that they do not provide power for a certain period, e.g. during the weekend and accordingly, the devices plugged into the ports are off (like a switchable power socket)?

**Comment by Kienz** [comment]
Yes. Just use HomeKit automations to activate/deactivate the ports.

**Comment by BeckeBauer** [comment]
I am completely new to homebridge - is `HomeKit automations` another plugin? Any hint to a tutorial or wiki is appreciated (my own search always leads to an apple system which I do not possess)

**Comment by Kienz** [comment]
Homebridge is normally used to bring devices to HomeKit which not natively support HomeKit.
An in Apple Home you can can control all devices and you can define automations.

**Comment by BeckeBauer** [comment]
I was not aware that homebridge is the link to the "apple world". I am looking for an option to set a time schedule for the poe ports of my unifi switch and stumbled over a thread where homebridge was mentioned and thought, your plugin provide this option without the need to have apple products. Sorry for not reading first...

**Comment by BeckeBauer** [comment]
I was not aware that homebridge is the link to the "apple world". I am looking for an option to set a time schedule for the poe ports of my unifi switch and stumbled over a thread where homebridge was mentioned and thought, your plugin provide this option without the need to have apple products. Sorry for not reading first...

**Comment by BeckeBauer** [comment]
> Homebridge is normally used to bring devices to HomeKit which not natively support HomeKit. An in Apple Home you can can control all devices and you can define automations.

I was not aware that homebridge is the link to the "apple world". I am looking for an option to set a time schedule for the poe ports of my unifi switch and stumbled over a thread where homebridge was mentioned and thought, your plugin provide this option without the need to have apple products. Sorry for not reading first...
