### ISSUE TITLE
Can only control ports that have existing port overrides

### ISSUE THREAD

**Issue by akosut** [Kienz/homebridge-unifi-poe-control#3]
Took me a lot of trial and error to figure out why only some arbitrary ports on my switches would show up as HomeKit accessories and others were ignored completed.  I finally read through the code and enabled debug logging and figured it out: the code looks at the port_overrides dictionary for the switch to figure out whether to set up the accessory.  But this only exists for switch ports that have had an override set in the Unifi network controller.  If you have not done this, the Unifi-PoE-Control plugin ignores the port and does not create the HomeKit accessory.

I understand why this might be difficult to fix, since the code modifies the existing override rather than creating a new one, but it would be great if the documentation had a note explaining this.  Once I understood this, it was very easy to fix: I toggled the PoE setting in the Unifi network settings for the port, and the plugin picked it up and created the accessory on the next refresh.

**Comment by Kienz** [comment]
I will look at it - maybe there are other options to config the ports (see also #4).
In the meantime I will update the README.

I think I can fix this in the next release - if no port_override for this port exists I add a new config. Should be fixed on the next release.

**Comment by Kienz** [comment]
Fixed (Release v1.2.0)
