### ISSUE TITLE
Multiple ports controlled at the same time

### ISSUE THREAD

**Issue by cwfeldmann** [Kienz/homebridge-unifi-poe-control#5]
We have a few items that we control all at the same time and would love to be able to automate them to a schedule. I've programed each port into the plugin however when I group them in HomeKit as one tile, only one in the group responds to the on/off action. Same thing occurs when controlling the three items with a scene. When the plugin sends its commands, is it only able to send one command at a time to the switch?

I've considered an SSH solution but don't have enough knowledge about it to put a dent in that plan. This plugin is much more elegant but I'm having this one tiny snafu.

Thanks for considering and thank you for the plugin.

**Comment by adityachugh** [comment]
Hi, I'm experiencing this exact same issue, I'm trying to control 3 POE devices in a scene. Only 1 of the devices is controlled, and the others return to the previous state. @cwfeldmann have you been able to find a workaround for this?

**Comment by cwfeldmann** [comment]
@adityachugh – that's a relief that I wasn't the only one! I'll admit, it's FAR from an ideal solution but it has seemed to work.

I had to implement a relay system with another Homebridge switch that allows delays. I've put a delay of about 500ms for each one. https://github.com/nitaybz/homebridge-delay-switch#readme

We use this for 3 "PTZ Optics" branded cameras at my church. When one camera is triggered in the Home app - a series of automations cascade through with these "Delay" switches between each step.

@Kienz, I'm curious – If there could be a way to implement delay options for each switch we setup in the PoE plugin you made here. Could that help "cue up" commands to the server? I'm assuming the issue is when HomeBridge sends two commands at once, the UI Server doesn't know what to do with both those commands. If possible, it could help space out those commands with the understanding that I control the delay at which each port's command gets sent when I setup the switch for that port.

Example: In the plugin, I could dictate that Camera 1 set to a 0ms delay, Cam 2 is set to 500ms. Cam 3 is set to 1000ms. I could scale this to satisfy any number of POE ports myself upon setup understanding that some might have delays when I call for them based on what I set in the plugin.

**Comment by Daveblanche** [comment]
@cwfeldmann  I use a shortcut in HomeKit to add delays.

**Comment by athurdent** [comment]
+1 on this issue, just pulled out my hair why my second PoE device on the same switch never came up.

**Comment by Kienz** [comment]
Should be fixed with release 1.3.0

**Comment by cwfeldmann** [comment]
@Kienz – Just wanted to thank you for this fix. Seems as though it's been working really well over the last 10 months.
