### ISSUE TITLE
log clutter

### ISSUE THREAD

**Issue by ac4lt** [Kienz/homebridge-unifi-poe-control#6]
thanks for this useful plugin!

Is there any chance the "Refreshing devices..." message can be removed or disabled? It really clutters up the home bridge log.

**Comment by stephanlinke87** [comment]
This can be done manually by updating node_modules\homebridge-unifi-poe-control\src\UniFiPoeControl.js, simply make look line 59 like this: 

`    //this.log.info('Refreshing devices...');
`

and restart homebridge. It will then not log anything on device updates :)

**Comment by jannemann** [comment]
This should be fixed with https://github.com/Kienz/homebridge-unifi-poe-control/pull/10
